title: selfie
description: An educational software system of a tiny self-compiling C compiler, a tiny self-executing MIPS emulator, and a tiny self-hosting MIPS hypervisor.
google_analytics: UA-3827654-1
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
